version: 0.2

phases:
  pre_build:
    commands:
      - echo nothing to download...
  build:
    commands:
      - echo Entered the build process...
      - mvn install
  post_build:
    commands:
      - echo build completed successfully...
      - cp /target/aws-codepipeline.war /opt/tomcat/webapps/
artifacts:
  files:
    - target/aws-codepipeline.war
    - appspec.yml
    - scripts/*
