#!/bin/bash


#1. search for PID
script_1="tomcat"
#2. store in a file - result
script_1_pid=`sudo ps -eaf | grep -m1 ${script_1}`
echo "${script_1_pid}" > /home/ec2-user/pid_1.txt

#3. wc lines
#tom_exists= wc -l $script_1_pid

#/home/ec2-user/pid_1.txt

#echo "${tom_exists}"


#sudo wc -l tom_exists > /home/ec2-user/pid_count.txt

sudo wc -l /home/ec2-user/pid_1.txt > /home/ec2-user/pid_count.txt


z=`cut -c 1-2 /home/ec2-user/pid_count.txt`

echo ${z}

if [ $z -gt 0 ]; then
echo "tomcat existis"
else
echo "if statement tomcat not exists"
fi
