#!/bin/bash
sudo yum update -y

#1. search for PID
script_1="tomcat"
#2. store in a file - result
script_1_pid=`sudo ps -eaf | grep -m1 ${script_1}`
echo "${script_1_pid}" > /home/ec2-user/pid_1.txt

#3. wc lines
tom_exists= sudo wc -l /home/ec2-user/pid_1.txt

if [tom_exists -eq 1 ]
then 
echo "tomcat existis"
else
echo "tomcat not exists"
fi
